// Zitrone — Copyright (C) 2026 Zitrone contributors
// Licensed under the GNU Affero General Public License v3.0 or later.
// See the LICENSE file in the repository root for full license text.
// SPDX-License-Identifier: AGPL-3.0-only

// ⚠️ This implementation has not undergone third-party security audit.
// See AUDIT.md in the repository root.

package com.zitrone.app.decoy

import com.zitrone.app.crypto.SignalProtocolManager
import org.signal.libsignal.protocol.IdentityKeyPair
import org.signal.libsignal.protocol.ecc.Curve
import java.security.SecureRandom
import java.util.Base64

/**
 * Key material for the synthetic relay account a vault addresses its cover traffic to.
 *
 * This is deliberately a SEPARATE, minimal path rather than a second [SignalProtocolManager]:
 * that class is bound to a [com.zitrone.app.crypto.ZitroneSignalStore] and every operation on it
 * persists into the vault's ordinary Signal-record space. The synthetic account needs exactly one
 * durable secret — its long-term identity keypair, which is what authenticates it to the relay —
 * and nothing else.
 *
 * **The prekey PRIVATE halves are generated and then DISCARDED, on purpose.** A real account keeps
 * them because peers establish X3DH sessions against its published bundle and it must decrypt what
 * arrives. Nothing ever decrypts a decoy: the ciphertext is random bytes by design (spec §2.3 — a
 * real ratchet with the synthetic peer would double the vault's reseal rate for no observable
 * gain), and the synthetic side acks and burns without reading. Keeping 100 one-time private
 * halves would therefore be pure durable cost for a capability that is ruled out. What IS uploaded
 * is a genuine, correctly-signed bundle of the same shape and batch size a real Android client
 * publishes, so the account is structurally an ordinary account.
 *
 * ⚠️ **"Discarded" means dropped to GC, and it cannot mean more than that — stated because the
 * unit's wipe discipline is otherwise absolute.** The one secret this file hands out as bytes, the
 * serialized identity keypair, is a `ByteArray` its owner zeroes on every abandon path. Prekey
 * private halves are never serialized: they exist only inside libsignal `ECPrivateKey` objects,
 * whose bytes live in Rust-owned memory behind a native handle. libsignal-client 0.46.0 exposes no
 * `close()`/`destroy()` on `ECPrivateKey` — `javap` shows `finalize()`, `serialize()`,
 * `calculateSignature`, `calculateAgreement`, `publicKey`, and nothing else — so the ONLY
 * deallocation path is finalization. (`Native.ECPrivateKey_Destroy` is reachable via
 * `unsafeNativeHandleWithoutGuard()`, and calling it would double-free when `finalize()` runs on
 * the same handle: memory corruption traded for a wipe.) The same residue applies to every
 * libsignal key this app creates, including the real account's identity in `SignalProtocolManager`;
 * it is not specific to cover traffic. What IS in our control is RESIDENCY, so the bundle is
 * generated by [generateBundle] immediately before the registration that consumes it rather than
 * before the proof-of-work solve — see [generateIdentity].
 *
 * All byte/base64 conventions mirror [SignalProtocolManager] exactly — raw 32-byte identity key on
 * the wire (the server validates `len == 32`), signatures over libsignal's 33-byte `serialize()`
 * form, `java.util.Base64` rather than `android.util.Base64` so this is exercisable off-device.
 *
 * Nothing here logs, and no method returns a private key to a caller other than the serialized
 * keypair the vault stores.
 */
object DecoyIdentity {

    /** Batch size for the uploaded one-time prekeys — the same a real client publishes. */
    private const val ONE_TIME_PREKEY_BATCH = SignalProtocolManager.ONE_TIME_PREKEY_BATCH

    /**
     * The one-time prekey ids this account publishes, and the ONLY ids a cover envelope's
     * `prekey_id` may legitimately name.
     *
     * `prekey_id` on a real envelope is the **recipient's** consumed one-time prekey id, not the
     * sender's: the sender fetches the peer's bundle and libsignal replays the consumed id until the
     * peer's reply completes the ratchet. For cover traffic the "recipient" is this vault's own
     * synthetic account, so the legitimate draw is the batch [generateBundle] uploaded for it — a
     * value outside this range is a fingerprint, and a random id in `[1, 0xFFFFFF]` is one with
     * near-certainty.
     *
     * Declared here rather than inline in [generateBundle] so the generator and the consumer read
     * one source. **This range is not recorded in the vault** — nothing durable stores which ids
     * were uploaded, so its authority rests entirely on [generateBundle] being unconditional about
     * them. `DecoyEnvelopeBuilderTest` pins that (in
     * `prekey_id is drawn from the synthetic account's OWN uploaded batch and mirrors the covered
     * width` — there is no separate `DecoyIdentityTest`): it asserts a generated bundle's ids are
     * exactly this range, so a future change to the allocation cannot silently strand
     * already-provisioned accounts whose real batch this range would then misdescribe.
     */
    val ONE_TIME_PREKEY_IDS: IntRange = 1..ONE_TIME_PREKEY_BATCH

    /**
     * The id the relay would hand out on the first bundle fetch for this account, and therefore the
     * id a genuine first message to it would carry.
     *
     * Not an arbitrary pick from [ONE_TIME_PREKEY_IDS]: `Store.ConsumeOneTimePrekey` pops
     * `ORDER BY prekey_id LIMIT 1`, so the lowest unconsumed id is the one issued, and the synthetic
     * account has consumed none. Drawing a random member of the range instead would be wrong 99
     * times out of 100 against the very query that decides the answer.
     *
     * **Residual, stated because it cannot be closed here:** nothing ever fetches this account's
     * bundle, so the relay can see that the named id was never actually consumed. Closing that would
     * mean a real bundle fetch and a real session — which §2.3 rules out — and it is relay-visible
     * only, which the spec's §1 threat model already concedes in full.
     */
    val FIRST_ONE_TIME_PREKEY_ID: Int = ONE_TIME_PREKEY_IDS.first

    /**
     * The signed prekey id this account publishes — the value a genuine first message to it carries
     * in `signed_pre_key_id`. Ids start at 1 exactly as a fresh real account's allocator does.
     */
    const val SIGNED_PREKEY_ID: Int = 1

    /**
     * The long-term secret alone: everything the proof-of-work binds against, and everything the
     * vault ever stores. Held across the (seconds-long) PoW solve, unlike the prekey bundle.
     */
    class Identity(
        /** libsignal `IdentityKeyPair.serialize()` — PUBLIC ‖ PRIVATE. The vault stores this. */
        val identityKeyPair: ByteArray,
        /** 14-bit registration id, per the Signal spec (1..16380). Sent, never stored. */
        val registrationId: Int,
    ) {
        val identityKeyBase64: String get() = publicKeyBase64(identityKeyPair)
    }

    /** A registered bundle plus the serialized identity the vault must keep. */
    class Material(
        private val identity: Identity,
        val signedPreKey: SignalProtocolManager.SignedPreKeyDto,
        val oneTimePreKeys: List<SignalProtocolManager.OneTimePreKeyDto>,
    ) {
        val identityKeyPair: ByteArray get() = identity.identityKeyPair
        val registrationId: Int get() = identity.registrationId
        val identityKeyBase64: String get() = identity.identityKeyBase64
    }

    /**
     * Generate the long-term identity. Purely local — no network, no durable write. The caller owns
     * [Identity.identityKeyPair] and is responsible for wiping it if the registration it was
     * generated for never commits.
     *
     * Split from [generateBundle] deliberately: the proof-of-work solve between them costs seconds
     * of CPU, and the prekey private halves cannot be zeroed (see the class kdoc), so they are not
     * created until the registration that consumes them is the very next call.
     */
    fun generateIdentity(random: SecureRandom = SecureRandom()): Identity {
        val identity = IdentityKeyPair.generate()
        // 14-bit registration id per the Signal spec (1..16380) — identical to
        // SignalProtocolManager.ensureIdentity, so nothing about this account's registration is
        // drawn from a different distribution than a real one's.
        return Identity(identity.serialize(), random.nextInt(16380) + 1)
    }

    /**
     * Generate the registerable prekey bundle for [identity] — a genuine, correctly-signed bundle
     * of the shape and batch size a real Android client publishes.
     *
     * Call this immediately before `register`: it creates [ONE_TIME_PREKEY_BATCH] + 1 libsignal
     * private keys whose bytes are outside this code's reach (class kdoc), so their residency is
     * the only thing that can be kept short.
     */
    fun generateBundle(identity: Identity): Material {
        val keyPair = IdentityKeyPair(identity.identityKeyPair)

        // Signed prekey: sign the 33-byte serialize() form (NOT the raw 32-byte wire form), the
        // representation a receiving peer reconstructs and verifies against — see the long note in
        // SignalProtocolManager.generateSignedPreKey. Signing the wrong representation would
        // produce a bundle the relay rejects with bad_prekey_signature.
        val signedPreKeyPair = Curve.generateKeyPair()
        val signature = Curve.calculateSignature(keyPair.privateKey, signedPreKeyPair.publicKey.serialize())
        val signedPreKey = SignalProtocolManager.SignedPreKeyDto(
            // Ids start at 1 like a fresh real account's allocator does.
            id = SIGNED_PREKEY_ID,
            publicKeyBase64 = encode(signedPreKeyPair.publicKey.getPublicKeyBytes()),
            signatureBase64 = encode(signature),
            timestampMs = System.currentTimeMillis(),
        )

        val oneTimePreKeys = ONE_TIME_PREKEY_IDS.map { id ->
            SignalProtocolManager.OneTimePreKeyDto(
                id = id,
                publicKeyBase64 = encode(Curve.generateKeyPair().publicKey.getPublicKeyBytes()),
            )
        }

        return Material(
            identity = identity,
            signedPreKey = signedPreKey,
            oneTimePreKeys = oneTimePreKeys,
        )
    }

    /**
     * The raw 32-byte identity public key, base64 — the wire form the relay validates
     * (`len(identity_key) == 32`; libsignal's `serialize()` would add a 0x05 type prefix and be
     * rejected as `bad_identity_key`). Also what the registration proof-of-work binds against.
     */
    fun publicKeyBase64(identityKeyPair: ByteArray): String =
        encode(publicKeyBytes(identityKeyPair))

    /** The raw 32-byte identity public key. */
    fun publicKeyBytes(identityKeyPair: ByteArray): ByteArray =
        IdentityKeyPair(identityKeyPair).publicKey.publicKey.getPublicKeyBytes()

    /**
     * Sign the relay's timestamped login challenge with the synthetic identity key — the same
     * XEdDSA-over-Curve25519 scheme [SignalProtocolManager.signLoginChallenge] uses, so the
     * account authenticates exactly as an ordinary Android account does.
     */
    fun signLoginChallenge(identityKeyPair: ByteArray, challenge: String): String =
        encode(
            IdentityKeyPair(identityKeyPair).privateKey
                .calculateSignature(challenge.toByteArray(Charsets.UTF_8)),
        )

    // java.util.Base64 (not android.util) — no Android runtime dependency, so every byte path
    // here is exercisable in an ordinary unit test. minSdk is 26, where java.util.Base64 exists.
    private fun encode(bytes: ByteArray): String = Base64.getEncoder().encodeToString(bytes)
}
