// Zitrone — Copyright (C) 2026 Zitrone contributors
// Licensed under the GNU Affero General Public License v3.0 or later.
// See the LICENSE file in the repository root for full license text.
// SPDX-License-Identifier: AGPL-3.0-only

import { describe, expect, it } from "vitest";
import { fromBase64 } from "./encoding.js";
import {
  classifyBundleIdentity,
  generateIdentityKeyPair,
  generateSignedPrekey,
} from "./keys.js";
import { signedPrekeyMessage, verifyXEdDSA } from "./xeddsa.js";
import { x3dhInitiate } from "./x3dh.js";

// The SAME vectors as server/internal/auth/xeddsa_test.go — real signatures
// produced by libsignal-client 0.46.0 (the exact library apps/android and
// apps/ios sign with), NOT generated by this TypeScript code or the Go port.
// Deliberately shared byte-for-byte with the server's test suite: the review
// requirement on this port is that it matches the server's verifier in
// behavior, and the strongest cheap check is both implementations passing the
// identical accept/reject battery. Regeneration instructions live in
// xeddsa_test.go.
const IDENTITY_RAW32_B64 = "1d8NiGPds3c2oB+Uw7W3RZb6lKRaizNEa3Ci1/g3plY=";
const OTHER_IDENTITY_RAW32_B64 = "wcicHYcoPMrc9XU8FdZOqbIqQBH7Q7i4u/Afk9t1sRo=";

// Vector A: a login-challenge-shaped message — raw UTF-8, unprefixed.
const CHALLENGE_B64 =
  "c3VibGVtb25hYmxlLWxvZ2luOjExMTExMTExLTIyMjItMzMzMy00NDQ0LTU1NTU1NTU1NTU1NToxNzUyMDAwMDAw";
const LOGIN_SIG_B64 =
  "GPHNmR/wnzDYuZ8oYiIIYlHRRYtijLNjG5Wn0aervonrML+mZe0ZR7JNMUpBalHCW1s0gWd2e+YioT8gC1U2hw==";

// Vector B: a signed-prekey-shaped message — the 33-byte libsignal
// serialize() form (djbType byte + raw 32-byte key).
const SPK_SERIALIZE33_B64 = "Bb9jSqZowLvh+Vj9B0CTBfIlH1WlYBd7TVN2avIkZhNh";
const SPK_RAW32_B64 = "v2NKpmjAu+H5WP0HQJMF8iUfVaVgF3tNU3Zq8iRmE2E=";
const SPK_SIG_B64 =
  "XGpVH3ElT7yNQPh0WvAalHvjG8AZry91SOCy7zqmIPU0TKeMxWRgahAletwDrvKpVCwAu1YWTr5nQ4WLPCW+gw==";

// Degenerate public key: u = p−1 ≡ −1 (mod p), where the Montgomery→Edwards
// map is undefined. Same constant as the Go test added on PR #22 review.
const DEGENERATE_U_MINUS_ONE_B64 = "7P///////////////////////////////////////38=";

describe("verifyXEdDSA (port of server VerifyXEdDSA — shared vector battery)", () => {
  it("accepts a real libsignal login-challenge signature", async () => {
    expect(
      await verifyXEdDSA(
        await fromBase64(IDENTITY_RAW32_B64),
        await fromBase64(CHALLENGE_B64),
        await fromBase64(LOGIN_SIG_B64),
      ),
    ).toBe(true);
  });

  it("accepts a real libsignal signed-prekey signature over the 33-byte form", async () => {
    expect(
      await verifyXEdDSA(
        await fromBase64(IDENTITY_RAW32_B64),
        await fromBase64(SPK_SERIALIZE33_B64),
        await fromBase64(SPK_SIG_B64),
      ),
    ).toBe(true);
  });

  it("signedPrekeyMessage reconstructs the exact 33-byte signed form", async () => {
    expect(signedPrekeyMessage(await fromBase64(SPK_RAW32_B64))).toEqual(
      await fromBase64(SPK_SERIALIZE33_B64),
    );
  });

  it("rejects a bit-flipped signature", async () => {
    const sig = await fromBase64(LOGIN_SIG_B64);
    sig[0]! ^= 0x01;
    expect(
      await verifyXEdDSA(await fromBase64(IDENTITY_RAW32_B64), await fromBase64(CHALLENGE_B64), sig),
    ).toBe(false);
  });

  it("rejects the wrong message", async () => {
    expect(
      await verifyXEdDSA(
        await fromBase64(IDENTITY_RAW32_B64),
        new TextEncoder().encode("not the signed message"),
        await fromBase64(LOGIN_SIG_B64),
      ),
    ).toBe(false);
  });

  it("rejects a prekey signature verified against the raw 32-byte form", async () => {
    // The signature covers serialize() (33 bytes), not the raw wire form —
    // the exact mistake signedPrekeyMessage exists to prevent.
    expect(
      await verifyXEdDSA(
        await fromBase64(IDENTITY_RAW32_B64),
        await fromBase64(SPK_RAW32_B64),
        await fromBase64(SPK_SIG_B64),
      ),
    ).toBe(false);
  });

  it("rejects the wrong identity key", async () => {
    expect(
      await verifyXEdDSA(
        await fromBase64(OTHER_IDENTITY_RAW32_B64),
        await fromBase64(CHALLENGE_B64),
        await fromBase64(LOGIN_SIG_B64),
      ),
    ).toBe(false);
  });

  it("rejects malformed lengths", async () => {
    const pub = await fromBase64(IDENTITY_RAW32_B64);
    const msg = await fromBase64(CHALLENGE_B64);
    const sig = await fromBase64(LOGIN_SIG_B64);
    expect(await verifyXEdDSA(pub.slice(0, 31), msg, sig)).toBe(false);
    expect(await verifyXEdDSA(concatBytes(pub, 0x00), msg, sig)).toBe(false);
    expect(await verifyXEdDSA(pub, msg, sig.slice(0, 63))).toBe(false);
    expect(await verifyXEdDSA(pub, msg, concatBytes(sig, 0x00))).toBe(false);
  });

  it("rejects the degenerate u = −1 public key", async () => {
    expect(
      await verifyXEdDSA(
        await fromBase64(DEGENERATE_U_MINUS_ONE_B64),
        await fromBase64(CHALLENGE_B64),
        await fromBase64(LOGIN_SIG_B64),
      ),
    ).toBe(false);
  });
});

describe("classifyBundleIdentity (client-side try-both, per-platform families)", () => {
  it("classifies a web/desktop bundle as ed25519", async () => {
    const identity = await generateIdentityKeyPair();
    const spk = await generateSignedPrekey(identity, 1);
    expect(await classifyBundleIdentity(spk.publicKey, spk.signature, identity.publicKey)).toBe(
      "ed25519",
    );
  });

  it("classifies a real Android-family (XEdDSA-signed) bundle as curve25519", async () => {
    expect(
      await classifyBundleIdentity(
        await fromBase64(SPK_RAW32_B64),
        await fromBase64(SPK_SIG_B64),
        await fromBase64(IDENTITY_RAW32_B64),
      ),
    ).toBe("curve25519");
  });

  it("fails closed (null) when neither scheme verifies", async () => {
    const identity = await generateIdentityKeyPair();
    const spk = await generateSignedPrekey(identity, 1);
    const wrongSig = spk.signature.slice();
    wrongSig[0]! ^= 0x01;
    expect(await classifyBundleIdentity(spk.publicKey, wrongSig, identity.publicKey)).toBeNull();
    // Cross-family confusion must also fail closed: an Android signature
    // presented under a web identity key, and vice versa.
    expect(
      await classifyBundleIdentity(
        await fromBase64(SPK_RAW32_B64),
        await fromBase64(SPK_SIG_B64),
        identity.publicKey,
      ),
    ).toBeNull();
    expect(
      await classifyBundleIdentity(
        spk.publicKey,
        spk.signature,
        await fromBase64(IDENTITY_RAW32_B64),
      ),
    ).toBeNull();
  });
});

describe("x3dhInitiate against an Android-family bundle", () => {
  it("verifies the real XEdDSA bundle and reports its family", async () => {
    const me = await generateIdentityKeyPair();
    const init = await x3dhInitiate(me, {
      identityKey: await fromBase64(IDENTITY_RAW32_B64),
      signedPrekey: {
        id: 7,
        publicKey: await fromBase64(SPK_RAW32_B64),
        signature: await fromBase64(SPK_SIG_B64),
      },
      oneTimePrekey: null,
    });
    expect(init.identityKeyFamily).toBe("curve25519");
    expect(init.ephemeralPublicKey).toHaveLength(32);
  });

  it("still reports ed25519 for a web-family bundle", async () => {
    const me = await generateIdentityKeyPair();
    const them = await generateIdentityKeyPair();
    const spk = await generateSignedPrekey(them, 1);
    const init = await x3dhInitiate(me, {
      identityKey: them.publicKey,
      signedPrekey: { id: 1, publicKey: spk.publicKey, signature: spk.signature },
      oneTimePrekey: null,
    });
    expect(init.identityKeyFamily).toBe("ed25519");
  });

  it("rejects a bundle that verifies under neither scheme (fails closed)", async () => {
    const me = await generateIdentityKeyPair();
    const them = await generateIdentityKeyPair();
    const spk = await generateSignedPrekey(them, 1);
    const wrongSig = spk.signature.slice();
    wrongSig[10]! ^= 0xff;
    await expect(
      x3dhInitiate(me, {
        identityKey: them.publicKey,
        signedPrekey: { id: 1, publicKey: spk.publicKey, signature: wrongSig },
        oneTimePrekey: null,
      }),
    ).rejects.toThrow("prekey bundle signature verification failed");
  });
});

function concatBytes(bytes: Uint8Array, extra: number): Uint8Array {
  const out = new Uint8Array(bytes.length + 1);
  out.set(bytes);
  out[bytes.length] = extra;
  return out;
}
