// Sublemonable — Copyright (C) 2026 Sublemonable contributors
// Licensed under the GNU Affero General Public License v3.0 or later.
// See the LICENSE file in the repository root for full license text.
// SPDX-License-Identifier: AGPL-3.0-only

package auth

import (
	"encoding/base64"
	"testing"
)

// All vectors below are real signatures produced by libsignal-client 0.46.0
// (org.signal:libsignal-client, the exact library apps/android and apps/ios
// sign with) — NOT generated by this Go code or any hand-derived
// implementation. Deliberately not self-generated: a bug in VerifyXEdDSA's
// conversion could otherwise pass its own test by construction. Regenerate
// with a small Java program calling IdentityKeyPair.generate() +
// Curve.calculateSignature() against the vendored jar if these ever need to
// change; see .l00prite/ledger.md Run 14 for the exact commands used.
const (
	xeddsaIdentityRaw32B64 = "1d8NiGPds3c2oB+Uw7W3RZb6lKRaizNEa3Ci1/g3plY="

	// Vector A: a login-challenge-shaped message (VerifyLogin's code path) —
	// the raw UTF-8 challenge string, unprefixed.
	xeddsaChallengeB64 = "c3VibGVtb25hYmxlLWxvZ2luOjExMTExMTExLTIyMjItMzMzMy00NDQ0LTU1NTU1NTU1NTU1NToxNzUyMDAwMDAw"
	xeddsaLoginSigB64  = "GPHNmR/wnzDYuZ8oYiIIYlHRRYtijLNjG5Wn0aervonrML+mZe0ZR7JNMUpBalHCW1s0gWd2e+YioT8gC1U2hw=="

	// Vector B: a signed-prekey-shaped message (Register/UploadPrekeys' code
	// path) — the 33-byte libsignal serialize() form (djbType byte + the
	// raw 32-byte key), matching signedPrekeyMessage() in handlers.go.
	xeddsaSpkSerialize33B64 = "Bb9jSqZowLvh+Vj9B0CTBfIlH1WlYBd7TVN2avIkZhNh"
	xeddsaSpkRaw32B64       = "v2NKpmjAu+H5WP0HQJMF8iUfVaVgF3tNU3Zq8iRmE2E="
	xeddsaSpkSigB64         = "XGpVH3ElT7yNQPh0WvAalHvjG8AZry91SOCy7zqmIPU0TKeMxWRgahAletwDrvKpVCwAu1YWTr5nQ4WLPCW+gw=="
)

func mustDecode(t *testing.T, s string) []byte {
	t.Helper()
	b, err := base64.StdEncoding.DecodeString(s)
	if err != nil {
		t.Fatal(err)
	}
	return b
}

func TestVerifyXEdDSA_LoginChallenge_Accepted(t *testing.T) {
	pub := mustDecode(t, xeddsaIdentityRaw32B64)
	msg := mustDecode(t, xeddsaChallengeB64)
	sig := mustDecode(t, xeddsaLoginSigB64)
	if !VerifyXEdDSA(pub, msg, sig) {
		t.Fatal("real libsignal XEdDSA login signature was rejected")
	}
}

func TestVerifyXEdDSA_SignedPrekey_Accepted(t *testing.T) {
	pub := mustDecode(t, xeddsaIdentityRaw32B64)
	msg := mustDecode(t, xeddsaSpkSerialize33B64)
	sig := mustDecode(t, xeddsaSpkSigB64)
	if !VerifyXEdDSA(pub, msg, sig) {
		t.Fatal("real libsignal XEdDSA signed-prekey signature was rejected")
	}
}

func TestVerifyXEdDSA_RejectsBitFlippedSignature(t *testing.T) {
	pub := mustDecode(t, xeddsaIdentityRaw32B64)
	msg := mustDecode(t, xeddsaChallengeB64)
	sig := mustDecode(t, xeddsaLoginSigB64)
	sig[0] ^= 0x01
	if VerifyXEdDSA(pub, msg, sig) {
		t.Fatal("bit-flipped signature was accepted")
	}
}

func TestVerifyXEdDSA_RejectsWrongMessage(t *testing.T) {
	pub := mustDecode(t, xeddsaIdentityRaw32B64)
	sig := mustDecode(t, xeddsaLoginSigB64)
	if VerifyXEdDSA(pub, []byte("not the signed message"), sig) {
		t.Fatal("signature verified against the wrong message")
	}
}

// The signed-prekey signature covers the 33-byte serialize() form, not the
// raw 32-byte wire form the server stores/receives — verifying against the
// raw form must fail. This is the exact case signedPrekeyMessage() in
// handlers.go exists to prevent (see Run 13's client-side finding).
func TestVerifyXEdDSA_SignedPrekey_RejectsUnprefixedMessage(t *testing.T) {
	pub := mustDecode(t, xeddsaIdentityRaw32B64)
	rawMsg := mustDecode(t, xeddsaSpkRaw32B64)
	sig := mustDecode(t, xeddsaSpkSigB64)
	if VerifyXEdDSA(pub, rawMsg, sig) {
		t.Fatal("signature over the 33-byte serialize() form verified against the raw 32-byte form")
	}
}

func TestVerifyXEdDSA_RejectsWrongKey(t *testing.T) {
	otherPub := mustDecode(t, loginTestOtherRaw32B64) // a different real identity key
	msg := mustDecode(t, xeddsaChallengeB64)
	sig := mustDecode(t, xeddsaLoginSigB64)
	if VerifyXEdDSA(otherPub, msg, sig) {
		t.Fatal("signature verified under the wrong identity key")
	}
}

func TestVerifyXEdDSA_RejectsMalformedLengths(t *testing.T) {
	pub := mustDecode(t, xeddsaIdentityRaw32B64)
	msg := mustDecode(t, xeddsaChallengeB64)
	sig := mustDecode(t, xeddsaLoginSigB64)

	if VerifyXEdDSA(pub[:31], msg, sig) {
		t.Fatal("accepted a 31-byte public key")
	}
	if VerifyXEdDSA(append(append([]byte{}, pub...), 0x00), msg, sig) {
		t.Fatal("accepted a 33-byte public key")
	}
	if VerifyXEdDSA(pub, msg, sig[:63]) {
		t.Fatal("accepted a 63-byte signature")
	}
	if VerifyXEdDSA(pub, msg, append(append([]byte{}, sig...), 0x00)) {
		t.Fatal("accepted a 65-byte signature")
	}
}

// Degenerate public key: u = -1 (mod p), i.e. mont_x+1 = 0. The birational
// map ed_y = (mont_x-1)/(mont_x+1) is undefined here — field.Element.Invert
// returns 0 rather than erroring on a zero input, so without an explicit
// check this would silently produce edY = 0 and hand a meaningless key to
// ed25519.Verify instead of failing deterministically (review: Copilot on
// PR #22). u = p-1, little-endian encoded, top bit already clear.
const xeddsaDegenerateMontgomeryMinusOneB64 = "7P///////////////////////////////////////38="

func TestVerifyXEdDSA_RejectsDegenerateMontgomeryMinusOne(t *testing.T) {
	pub := mustDecode(t, xeddsaDegenerateMontgomeryMinusOneB64)
	msg := mustDecode(t, xeddsaChallengeB64)
	sig := mustDecode(t, xeddsaLoginSigB64)
	if VerifyXEdDSA(pub, msg, sig) {
		t.Fatal("accepted a signature under the degenerate u=-1 public key")
	}
}
